### ISSUE TITLE
Last digit of Luigi's score missing

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade-MarioBros_MiSTer#13]
Player 2's score in the top right corner is missing the last digit making the game ten times harder for Luigi compared to Mario :)

**Comment by bellwood420** [comment]
Thanks. Good catch :)
Not only the last digit, rightmost background tiles are not displayed.
This is exactly a bug caused by my massive stability fix in April.
I'll investigate it.
